[2024-06-27T03:40:37.069+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: coba_ds_v4.load_gbq scheduled__2024-06-25T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
