[2024-06-26T14:09:13.398+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T14:09:13.455+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peduli_pintar_elt_all_dags_v1.cleaning_raw_data scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-26T14:09:13.470+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peduli_pintar_elt_all_dags_v1.cleaning_raw_data scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-26T14:09:13.471+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 5
[2024-06-26T14:09:13.495+0000] {taskinstance.py:2330} INFO - Executing <Task(CleaningData): cleaning_raw_data> on 2024-06-23 00:00:00+00:00
[2024-06-26T14:09:13.511+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=224) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T14:09:13.521+0000] {standard_task_runner.py:63} INFO - Started process 237 to run task
[2024-06-26T14:09:13.527+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'peduli_pintar_elt_all_dags_v1', 'cleaning_raw_data', 'scheduled__2024-06-23T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/etl_all_dags.py', '--cfg-path', '/tmp/tmprqdzbn8c']
[2024-06-26T14:09:13.537+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask cleaning_raw_data
[2024-06-26T14:09:13.691+0000] {task_command.py:426} INFO - Running <TaskInstance: peduli_pintar_elt_all_dags_v1.cleaning_raw_data scheduled__2024-06-23T00:00:00+00:00 [running]> on host 7ecff3f83b62
[2024-06-26T14:09:13.932+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kelompok 5 Capstone DE' AIRFLOW_CTX_DAG_ID='peduli_pintar_elt_all_dags_v1' AIRFLOW_CTX_TASK_ID='cleaning_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-23T00:00:00+00:00'
[2024-06-26T14:09:13.935+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T14:09:14.903+0000] {logging_mixin.py:188} INFO - 196
[2024-06-26T14:09:14.960+0000] {logging_mixin.py:188} INFO - Tidak ada data duplikat pada Donation
[2024-06-26T14:09:15.032+0000] {logging_mixin.py:188} INFO - Tidak ada missing value dalam Donation
[2024-06-26T14:09:15.053+0000] {logging_mixin.py:188} INFO - id                0
created_at        0
user_id           0
amount            0
status            0
image_payment     0
fundraising_id    0
dtype: int64
[2024-06-26T14:09:15.055+0000] {logging_mixin.py:188} INFO - 35
[2024-06-26T14:09:15.063+0000] {logging_mixin.py:188} INFO - Tidak ada data duplikat pada Fundraising
[2024-06-26T14:09:15.089+0000] {logging_mixin.py:188} INFO - Tidak ada missing value dalam Fundraising
[2024-06-26T14:09:15.095+0000] {logging_mixin.py:188} INFO - id                         0
created_at                 0
fundraising_category_id    0
organization_id            0
title                      0
image_url                  0
description                0
status                     0
goal_amount                0
current_progress           0
start_date                 0
end_date                   0
dtype: int64
[2024-06-26T14:09:15.097+0000] {logging_mixin.py:188} INFO - 133
[2024-06-26T14:09:15.105+0000] {logging_mixin.py:188} INFO - Tidak ada data duplikat pada Application
[2024-06-26T14:09:15.125+0000] {logging_mixin.py:188} INFO - Tidak ada missing value dalam Application
[2024-06-26T14:09:15.131+0000] {logging_mixin.py:188} INFO - id              0
created_at      0
ig_image_url    0
yt_image_url    0
user_id         0
vacancy_id      0
job             0
reason          0
age             0
dtype: int64
[2024-06-26T14:09:15.132+0000] {logging_mixin.py:188} INFO - 22
[2024-06-26T14:09:15.144+0000] {logging_mixin.py:188} INFO - Tidak ada data duplikat pada Volunteer_Vacancies
[2024-06-26T14:09:15.166+0000] {logging_mixin.py:188} INFO - Terdapat missing value dalam Volunteer_Vacancies
[2024-06-26T14:09:15.171+0000] {logging_mixin.py:188} INFO - id                        0
created_at                0
title                     0
organization_id           0
content_activity          0
location                  2
start_date                0
end_date                  0
target_volunteer          0
registered_volunteer      0
registration_deadline     0
image_url                 0
status                    0
link_wa                  20
dtype: int64
[2024-06-26T14:09:15.177+0000] {logging_mixin.py:188} INFO - 31
[2024-06-26T14:09:15.180+0000] {logging_mixin.py:188} INFO - Tidak ada data duplikat pada Testimoni_Volunteer
[2024-06-26T14:09:15.194+0000] {logging_mixin.py:188} INFO - Tidak ada missing value dalam Testimoni_Volunteer
[2024-06-26T14:09:15.198+0000] {logging_mixin.py:188} INFO - id            0
created_at    0
user_id       0
vacancy_id    0
testimoni     0
rating        0
dtype: int64
[2024-06-26T14:09:15.199+0000] {logging_mixin.py:188} INFO - 46
[2024-06-26T14:09:15.202+0000] {logging_mixin.py:188} INFO - Tidak ada data duplikat pada Bookmark_Fundraising
[2024-06-26T14:09:15.221+0000] {logging_mixin.py:188} INFO - Tidak ada missing value dalam Bookmark_Fundraising
[2024-06-26T14:09:15.228+0000] {logging_mixin.py:188} INFO - id                0
created_at        0
user_id           0
fundraising_id    0
dtype: int64
[2024-06-26T14:09:15.230+0000] {logging_mixin.py:188} INFO - 42
[2024-06-26T14:09:15.236+0000] {logging_mixin.py:188} INFO - Tidak ada data duplikat pada Bookmark_Volunteer
[2024-06-26T14:09:15.258+0000] {logging_mixin.py:188} INFO - Terdapat missing value dalam Bookmark_Volunteer
[2024-06-26T14:09:15.263+0000] {logging_mixin.py:188} INFO - id                         0
created_at                 0
user_id                    0
volunteer_vacancies_id     0
volunteer_vacancy_id      42
dtype: int64
[2024-06-26T14:09:15.272+0000] {logging_mixin.py:188} INFO - 28
[2024-06-26T14:09:15.277+0000] {logging_mixin.py:188} INFO - Tidak ada data duplikat pada Article
[2024-06-26T14:09:15.308+0000] {logging_mixin.py:188} INFO - Terdapat missing value dalam Article
[2024-06-26T14:09:15.318+0000] {logging_mixin.py:188} INFO - id            0
created_at    0
admin_id      5
title         0
content       0
image_url     0
dtype: int64
[2024-06-26T14:09:15.332+0000] {logging_mixin.py:188} INFO - 4
[2024-06-26T14:09:15.349+0000] {logging_mixin.py:188} INFO - Tidak ada data duplikat pada Fundraising_Categories
[2024-06-26T14:09:15.370+0000] {logging_mixin.py:188} INFO - Tidak ada missing value dalam Fundraising_Categories
[2024-06-26T14:09:15.388+0000] {logging_mixin.py:188} INFO - id            0
created_at    0
name          0
dtype: int64
[2024-06-26T14:09:15.391+0000] {logging_mixin.py:188} INFO - 132
[2024-06-26T14:09:15.410+0000] {logging_mixin.py:188} INFO - Tidak ada data duplikat pada User
[2024-06-26T14:09:15.445+0000] {logging_mixin.py:188} INFO - Terdapat missing value dalam User
[2024-06-26T14:09:15.456+0000] {logging_mixin.py:188} INFO - id               0
created_at       0
fullname         0
username         0
email            0
password         0
avatar           0
reset_token    126
no_telp          0
otp            126
dtype: int64
[2024-06-26T14:09:15.470+0000] {logging_mixin.py:188} INFO - 15
[2024-06-26T14:09:15.477+0000] {logging_mixin.py:188} INFO - Tidak ada data duplikat pada Organization
[2024-06-26T14:09:15.506+0000] {logging_mixin.py:188} INFO - Terdapat missing value dalam Organization
[2024-06-26T14:09:15.512+0000] {logging_mixin.py:188} INFO - id              0
created_at      0
name            0
description     0
avatar          0
is_verified     0
contact        14
start_date      0
website         0
instagram       0
no_rekening     0
dtype: int64
[2024-06-26T14:09:15.519+0000] {logging_mixin.py:188} INFO - 60
[2024-06-26T14:09:15.523+0000] {logging_mixin.py:188} INFO - Tidak ada data duplikat pada Bookmark_Articles
[2024-06-26T14:09:15.538+0000] {logging_mixin.py:188} INFO - Tidak ada missing value dalam Bookmark_Articles
[2024-06-26T14:09:15.543+0000] {logging_mixin.py:188} INFO - id            0
created_at    0
user_id       0
article_id    0
dtype: int64
[2024-06-26T14:09:15.544+0000] {logging_mixin.py:188} INFO - 55
[2024-06-26T14:09:15.547+0000] {logging_mixin.py:188} INFO - Tidak ada data duplikat pada Comments
[2024-06-26T14:09:15.562+0000] {logging_mixin.py:188} INFO - Terdapat missing value dalam Comments
[2024-06-26T14:09:15.582+0000] {logging_mixin.py:188} INFO - id              0
created_at      0
user_id         0
article_id      0
comment        28
total_likes     0
dtype: int64
[2024-06-26T14:09:15.586+0000] {logging_mixin.py:188} INFO - 107
[2024-06-26T14:09:15.590+0000] {logging_mixin.py:188} INFO - Tidak ada data duplikat pada Like Comments
[2024-06-26T14:09:15.602+0000] {logging_mixin.py:188} INFO - Tidak ada missing value dalam Like Comments
[2024-06-26T14:09:15.611+0000] {logging_mixin.py:188} INFO - id            0
created_at    0
user_id       0
comment_id    0
dtype: int64
[2024-06-26T14:09:26.955+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T14:09:30.526+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/custom_operator/etl_all_operator.py", line 140, in execute
    context['ti'].xcom_push(key='cleaned_dfs', value=clean_dfs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 221, in set
    dag_run_id = session.query(DagRun.id).filter_by(dag_id=dag_id, run_id=run_id).scalar()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2893, in scalar
    ret = self.one()
          ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2870, in one
    return self._iter().one()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-06-26T14:09:48.493+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=peduli_pintar_elt_all_dags_v1, task_id=cleaning_raw_data, run_id=scheduled__2024-06-23T00:00:00+00:00, execution_date=20240623T000000, start_date=20240626T140913, end_date=20240626T140948
[2024-06-26T14:09:48.668+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task cleaning_raw_data ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 237)
[2024-06-26T14:09:49.266+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T14:09:49.497+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T14:09:49.502+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
