[2024-06-26T14:08:02.443+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: peduli_pintar_elt_all_dags_v1.load_db_local scheduled__2024-06-25T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
