[2024-06-26T07:22:35.783+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: coba.extract_data scheduled__2024-06-24T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
