[2024-06-26T07:24:43.229+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T07:24:43.275+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coba.extract_data scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-06-26T07:24:43.291+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coba.extract_data scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-06-26T07:24:43.292+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-06-26T07:24:43.318+0000] {taskinstance.py:2330} INFO - Executing <Task(ExtractData): extract_data> on 2024-06-24 00:00:00+00:00
[2024-06-26T07:24:43.386+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=188) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T07:24:43.404+0000] {standard_task_runner.py:63} INFO - Started process 193 to run task
[2024-06-26T07:24:43.488+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'coba', 'extract_data', 'scheduled__2024-06-24T00:00:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/etl_all_dags.py', '--cfg-path', '/tmp/tmpy1r4eo_v']
[2024-06-26T07:24:43.527+0000] {standard_task_runner.py:91} INFO - Job 231: Subtask extract_data
[2024-06-26T07:24:43.787+0000] {task_command.py:426} INFO - Running <TaskInstance: coba.extract_data scheduled__2024-06-24T00:00:00+00:00 [running]> on host a8f5caccc1b1
[2024-06-26T07:24:44.286+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kelompok 5 Capstone DE' AIRFLOW_CTX_DAG_ID='coba' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-24T00:00:00+00:00'
[2024-06-26T07:24:44.290+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T07:24:44.388+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:44.860+0000] {sql.py:487} INFO - Running statement: SHOW TABLES, parameters: None
[2024-06-26T07:24:44.900+0000] {sql.py:496} INFO - Rows affected: 22
[2024-06-26T07:24:45.132+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:45.398+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM admin_notifications, parameters: None
[2024-06-26T07:24:45.438+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-26T07:24:45.505+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:47.772+0000] {sql.py:487} INFO - Running statement: SELECT * FROM admin_notifications, parameters: None
[2024-06-26T07:24:47.829+0000] {sql.py:496} INFO - Rows affected: 82
[2024-06-26T07:24:47.878+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:48.171+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM admins, parameters: None
[2024-06-26T07:24:48.203+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-26T07:24:48.248+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:48.528+0000] {sql.py:487} INFO - Running statement: SELECT * FROM admins, parameters: None
[2024-06-26T07:24:48.556+0000] {sql.py:496} INFO - Rows affected: 2
[2024-06-26T07:24:48.596+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:49.889+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM applications, parameters: None
[2024-06-26T07:24:49.924+0000] {sql.py:496} INFO - Rows affected: 11
[2024-06-26T07:24:49.965+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:50.328+0000] {sql.py:487} INFO - Running statement: SELECT * FROM applications, parameters: None
[2024-06-26T07:24:50.396+0000] {sql.py:496} INFO - Rows affected: 134
[2024-06-26T07:24:50.440+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:50.707+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM articles, parameters: None
[2024-06-26T07:24:50.740+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-26T07:24:50.776+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:52.058+0000] {sql.py:487} INFO - Running statement: SELECT * FROM articles, parameters: None
[2024-06-26T07:24:52.116+0000] {sql.py:496} INFO - Rows affected: 29
[2024-06-26T07:24:52.152+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:53.417+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM comments, parameters: None
[2024-06-26T07:24:53.448+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-26T07:24:53.485+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:53.786+0000] {sql.py:487} INFO - Running statement: SELECT * FROM comments, parameters: None
[2024-06-26T07:24:53.822+0000] {sql.py:496} INFO - Rows affected: 55
[2024-06-26T07:24:53.864+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:54.173+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM donation_comments, parameters: None
[2024-06-26T07:24:54.204+0000] {sql.py:496} INFO - Rows affected: 7
[2024-06-26T07:24:54.245+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:54.539+0000] {sql.py:487} INFO - Running statement: SELECT * FROM donation_comments, parameters: None
[2024-06-26T07:24:54.568+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-26T07:24:54.614+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:54.919+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM donation_manual_comments, parameters: None
[2024-06-26T07:24:54.951+0000] {sql.py:496} INFO - Rows affected: 7
[2024-06-26T07:24:54.988+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:56.278+0000] {sql.py:487} INFO - Running statement: SELECT * FROM donation_manual_comments, parameters: None
[2024-06-26T07:24:56.309+0000] {sql.py:496} INFO - Rows affected: 90
[2024-06-26T07:24:56.350+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:56.633+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM donation_manuals, parameters: None
[2024-06-26T07:24:56.666+0000] {sql.py:496} INFO - Rows affected: 9
[2024-06-26T07:24:56.707+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:56.982+0000] {sql.py:487} INFO - Running statement: SELECT * FROM donation_manuals, parameters: None
[2024-06-26T07:24:57.044+0000] {sql.py:496} INFO - Rows affected: 196
[2024-06-26T07:24:57.084+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:57.355+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM donations, parameters: None
[2024-06-26T07:24:57.384+0000] {sql.py:496} INFO - Rows affected: 11
[2024-06-26T07:24:57.428+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:57.739+0000] {sql.py:487} INFO - Running statement: SELECT * FROM donations, parameters: None
[2024-06-26T07:24:57.769+0000] {sql.py:496} INFO - Rows affected: 10
[2024-06-26T07:24:57.830+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:58.123+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM fundraising_categories, parameters: None
[2024-06-26T07:24:58.154+0000] {sql.py:496} INFO - Rows affected: 5
[2024-06-26T07:24:58.202+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:58.501+0000] {sql.py:487} INFO - Running statement: SELECT * FROM fundraising_categories, parameters: None
[2024-06-26T07:24:58.530+0000] {sql.py:496} INFO - Rows affected: 4
[2024-06-26T07:24:58.571+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:24:59.863+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM fundraisings, parameters: None
[2024-06-26T07:24:59.895+0000] {sql.py:496} INFO - Rows affected: 14
[2024-06-26T07:24:59.931+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:00.264+0000] {sql.py:487} INFO - Running statement: SELECT * FROM fundraisings, parameters: None
[2024-06-26T07:25:00.322+0000] {sql.py:496} INFO - Rows affected: 35
[2024-06-26T07:25:00.360+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:00.658+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM like_donation_comments, parameters: None
[2024-06-26T07:25:00.688+0000] {sql.py:496} INFO - Rows affected: 6
[2024-06-26T07:25:00.725+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:02.162+0000] {sql.py:487} INFO - Running statement: SELECT * FROM like_donation_comments, parameters: None
[2024-06-26T07:25:02.206+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-26T07:25:02.255+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:02.639+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM like_donation_manual_comments, parameters: None
[2024-06-26T07:25:02.670+0000] {sql.py:496} INFO - Rows affected: 6
[2024-06-26T07:25:02.712+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:03.473+0000] {sql.py:487} INFO - Running statement: SELECT * FROM like_donation_manual_comments, parameters: None
[2024-06-26T07:25:03.511+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-26T07:25:03.548+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:04.262+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM likes_comments, parameters: None
[2024-06-26T07:25:04.292+0000] {sql.py:496} INFO - Rows affected: 6
[2024-06-26T07:25:04.333+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:04.947+0000] {sql.py:487} INFO - Running statement: SELECT * FROM likes_comments, parameters: None
[2024-06-26T07:25:04.979+0000] {sql.py:496} INFO - Rows affected: 107
[2024-06-26T07:25:05.025+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:08.624+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM organizations, parameters: None
[2024-06-26T07:25:08.664+0000] {sql.py:496} INFO - Rows affected: 13
[2024-06-26T07:25:08.701+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:09.120+0000] {sql.py:487} INFO - Running statement: SELECT * FROM organizations, parameters: None
[2024-06-26T07:25:09.182+0000] {sql.py:496} INFO - Rows affected: 16
[2024-06-26T07:25:09.218+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:09.615+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM testimoni_volunteers, parameters: None
[2024-06-26T07:25:09.648+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-26T07:25:09.688+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:10.064+0000] {sql.py:487} INFO - Running statement: SELECT * FROM testimoni_volunteers, parameters: None
[2024-06-26T07:25:10.095+0000] {sql.py:496} INFO - Rows affected: 31
[2024-06-26T07:25:10.133+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:10.632+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM transactions, parameters: None
[2024-06-26T07:25:10.662+0000] {sql.py:496} INFO - Rows affected: 10
[2024-06-26T07:25:10.698+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:11.158+0000] {sql.py:487} INFO - Running statement: SELECT * FROM transactions, parameters: None
[2024-06-26T07:25:11.190+0000] {sql.py:496} INFO - Rows affected: 27
[2024-06-26T07:25:11.232+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:11.708+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM user_bookmark_articles, parameters: None
[2024-06-26T07:25:11.740+0000] {sql.py:496} INFO - Rows affected: 6
[2024-06-26T07:25:11.780+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:13.262+0000] {sql.py:487} INFO - Running statement: SELECT * FROM user_bookmark_articles, parameters: None
[2024-06-26T07:25:13.294+0000] {sql.py:496} INFO - Rows affected: 61
[2024-06-26T07:25:13.334+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:13.795+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM user_bookmark_fundraisings, parameters: None
[2024-06-26T07:25:13.826+0000] {sql.py:496} INFO - Rows affected: 6
[2024-06-26T07:25:13.861+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:15.272+0000] {sql.py:487} INFO - Running statement: SELECT * FROM user_bookmark_fundraisings, parameters: None
[2024-06-26T07:25:15.315+0000] {sql.py:496} INFO - Rows affected: 46
[2024-06-26T07:25:15.401+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:15.708+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM user_bookmark_volunteer_vacancies, parameters: None
[2024-06-26T07:25:15.754+0000] {sql.py:496} INFO - Rows affected: 7
[2024-06-26T07:25:15.795+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:16.101+0000] {sql.py:487} INFO - Running statement: SELECT * FROM user_bookmark_volunteer_vacancies, parameters: None
[2024-06-26T07:25:16.131+0000] {sql.py:496} INFO - Rows affected: 42
[2024-06-26T07:25:16.173+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-26T07:25:18.642+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM users, parameters: None
[2024-06-26T07:25:18.699+0000] {sql.py:496} INFO - Rows affected: 12
[2024-06-26T07:25:28.804+0000] {connection.py:513} ERROR - Unable to retrieve connection from secrets backend (MetastoreBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 508, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/metastore.py", line 43, in get_connection
    return MetastoreBackend._fetch_connection(conn_id, session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/metastore.py", line 74, in _fetch_connection
    conn = session.scalar(select(Connection).where(Connection.conn_id == conn_id).limit(1))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-06-26T07:25:32.575+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T07:25:33.837+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/custom_operator/etl_all_operator.py", line 53, in execute
    dataframes, table_names = self.extract_data_from_external_db(text_columns)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/custom_operator/etl_all_operator.py", line 34, in extract_data_from_external_db
    data = mysql_hook.get_records(f"SELECT * FROM {table}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 303, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/hooks/mysql.py", line 188, in get_conn
    conn = self.connection or self.get_connection(getattr(self, self.conn_name_attr))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `EXTERNAL_DB_CONN_CAPSTONE_DE` isn't defined
[2024-06-26T07:25:34.277+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=coba, task_id=extract_data, run_id=scheduled__2024-06-24T00:00:00+00:00, execution_date=20240624T000000, start_date=20240626T072443, end_date=20240626T072534
[2024-06-26T07:25:34.642+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 231 for task extract_data (The conn_id `EXTERNAL_DB_CONN_CAPSTONE_DE` isn't defined; 193)
[2024-06-26T07:25:34.891+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T07:25:35.265+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T07:25:35.278+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
